### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by mariavaghani** [mariavaghani/message_me#1]
- [ ] Add test to create user
- [ ] test to verify that username is unique
- [ ] fix sign up form alignment
- [ ] make chatrooms
- [ ] fix how time only shows up when it is more than 10 mins ago in messages
- [ ] deploy on heroku. maybe from a different OS?
